### ISSUE TITLE
password validation

### ISSUE THREAD

**Issue by kaverih** [foyarash/react-native-input-validation#2]
I am trying to validate password that contains one special character, one number, one uppercase. I tried it using input-validation, but i am getting error. can you please tell me how to validate it

**Comment by foyarash** [comment]
Please give me more details. What's the code you are using and what's the error you get?

**Comment by kaverih** [comment]
<InputValidation validator="data.email" onValidatorExecuted={isValid => console.log(isValid)} validatorExecutionDelay={100}/> I used this line of code for email, thats working fine. how to validate password using this InputValidation.

**Comment by foyarash** [comment]
`<InputValidation validator="password" onValidatorExecuted={isValid => console.log(isValid)} validatorExecutionDelay={100}/>` should be working. The requirements are described in the README

**Comment by Multi-Thinker** [comment]
+1, same. one upper, one lower, one special, one numeric till 8 characters long password never get validated.
