### ISSUE TITLE
Error border displays immediately

### ISSUE THREAD

**Issue by ga-reth** [foyarash/react-native-input-validation#3]
Firstly, thanks a lot for this repo - very useful!

I am using the below in my project and it works grand. However, the error border shows immediately when the component mounts? How can I stop this from showing until the user begins typing?

Thanks!

```
<InputValidation
         value={String(this.state.servings)}
         validator="^(?:[1-9]|10)$" 
         validatorExecutionDelay={100}
         errorMessage={'Enter a number 1-10'}
         onChangeText={(servings) => this.setState({ servings })}
         containerStyle={styles.inputStyle}
         errorInputContainerStyle={styles.error}
         textInputContainer={styles.inputStyle}
         textInput={styles.inputStyle}
/>
```

**Comment by foyarash** [comment]
Thanks for the kind words !

Your code is fine, there is just a little mistake in the component rendering, i will push a fix very soon, which means tomorrow i think

**Comment by foyarash** [comment]
@garethiv 1.1 is now avalaible with some additional features, please tell me if that solved your problem

**Comment by ga-reth** [comment]
@foyarash Works perfectly! Thanks a lot 👍
