### ISSUE TITLE
Problems with documentation

### ISSUE THREAD

**Issue by yadirhb** [foyarash/react-native-input-validation#4]
Hi there, I'm trying to make your library work, but I've kind of misunderstanding things in the description. What I'm implementing is a email input with an icon, kind of:
`
                        <InputValidation
                            validator="email"
                            iconComponent={<Icon/>}
                            iconName={'user'}
                            iconSize={30}
                            containerStyle={styles.formInput}
                            // onValidatorExecuted={isValid => alert(isValid)}
                        />
`
Where Icon is:
`import Icon from 'react-native-vector-icons/FontAwesome';`

For an unknown reason (to me) something is failing and I don't know why. 

![image](https://user-images.githubusercontent.com/6015754/39125396-30c7dac2-46d5-11e8-96d6-03c9d1e569b4.png)

This component seems great but I think a demo within will be better. Is there a place where I can find a working example of this?

**Comment by foyarash** [comment]
Hello,

Yes i am planning to create an example for the lib.

In the meantime, your error is happening because the iconComponent prop should look like 
`iconComponent={Icon}`

**Comment by yadirhb** [comment]
Working now!!! Thanks for that. Is there a way in which instead of
providing a component for icons, I could provide an instance already
configured with custom behaviour and so on? I think will be great If you
just add a type check for whatever the user wanted to provide, kind of
function returning a component, a component class perse or an instance of
component. Just some ideas... Thanks again with the quick support and
continue with the nice work!

**Comment by foyarash** [comment]
I'll take your feedbacks in consideration, thank you!
